services:

  redis:
    image: redis:7-alpine
    network_mode: host

  livekit-server:
    build:
      context: ./livekit-server
      dockerfile: Dockerfile

    network_mode: host

    depends_on:
      - redis


  sip:
    build:
      context: ./sip
      dockerfile: Dockerfile

    network_mode: host

    depends_on:
      - redis
      - livekit-server


    volumes:
      - ./sip/config.yaml:/sip/config.yaml:ro
